const code = [
  { name: 'AED', meaning: 'UAE Dirham' },
  { name: 'ARS', meaning: 'Argentine Peso' },
  { name: 'AUD', meaning: 'Australian Dollar' },
  { name: 'BGN', meaning: 'Bulgarian Lev' },
  { name: 'BRL', meaning: 'Braz Real' },
  { name: 'BSD', meaning: 'Bahamian Dollar' },
  { name: 'CAD', meaning: 'Canadian Dollar' },
  { name: 'CHF', meaning: 'Swiss Franc' },
  { name: 'CLP', meaning: 'Chilean Peso' },
  { name: 'CNY', meaning: 'Yuan' },
  { name: 'COP', meaning: 'Colombian Peso' },
  { name: 'CZK', meaning: 'Czech Koruna' },
  { name: 'DKK', meaning: 'Danish Krone' },
  { name: 'DOP', meaning: 'Dominican Peso' },
  { name: 'EGP', meaning: 'Egyptian Pound' },
  { name: 'EUR', meaning: 'Euro' },
  { name: 'FGD', meaning: 'Fijian Dollar' },
  { name: 'GBP', meaning: 'UK Pound St' },
  { name: 'GTQ', meaning: 'Guatemalan quetzal' },
  { name: 'HKD', meaning: 'Hong Kong Dollar' },
  { name: 'HRK', meaning: 'Croatian Kuna' },
  { name: 'HUF', meaning: 'Hungarian Forint' },
  { name: 'IDR', meaning: 'Indonesian Rupiah' },
  { name: 'ILS', meaning: 'Israeli Shekel' },
  { name: 'INR', meaning: 'Indian Rupee' },
  { name: 'ISK', meaning: 'Icelandic Krona' },
  { name: 'JPY', meaning: 'Japanese Yen' },
  { name: 'KRW', meaning: 'South Korean Won' },
  { name: 'KZT', meaning: 'Kazakhstani Tenge' },
  { name: 'MXN', meaning: 'Mexican Peso' },
  { name: 'MYR', meaning: 'Malaysian Ringgit' },
  { name: 'NOK', meaning: 'Norwegian Krone' },
  { name: 'NZD', meaning: 'New Zealand Dollar' },
  { name: 'PAB', meaning: 'Panamanian Balboa' },
  { name: 'PEN', meaning: 'Peruvian Sol' },
  { name: 'PHP', meaning: 'Philippine Peso' },
  { name: 'PKR', meaning: 'Pakistani Rupee' },
  { name: 'PLN', meaning: 'Polish Zloty' },
  { name: 'PYG', meaning: 'Paraguayan Guarani' },
  { name: 'RON', meaning: 'Romanian Leu' },
  { name: 'RUB', meaning: 'Russian Ruble' },
  { name: 'SAR', meaning: 'Saudi Riyal' },
  { name: 'SEK', meaning: 'Swedish Krona' },
  { name: 'SGD', meaning: 'Singapore Dollar' },
  { name: 'THB', meaning: 'Thai Baht' },
  { name: 'TRY', meaning: 'Turkish Lira' },
  { name: 'TWD', meaning: 'Taiwan Dollar' },
  { name: 'UAH', meaning: 'Ukrainian Hryvnia' },
  { name: 'USD', meaning: 'US Dollar' },
  { name: 'UYU', meaning: 'Peso Uruguayo' },
  { name: 'VND', meaning: 'Vietnamese Dong' },
  { name: 'ZAR', meaning: 'South African Rand' },
];

export default code;
